### ISSUE TITLE
test function not defined

### ISSUE THREAD

**Issue by famube** [ttthy/ure#3]
Hi, I'm trying to run the test phase, and got the following error. Besides that, which is the output file of the test phase and how do I interpret it? Can I get the clustered input lines (similar relations)?

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/users/fmuniz/mp/ure/ure/etypeplus/main.py", line 88, in <module>
    test(model, dataset, config)
NameError: name 'test' is not defined

**Comment by ttthy** [comment]
Hi @famube 
Sorry for the super slow response. I updated the script (import `test` function from `ure.train_eval `)
